### ISSUE TITLE
asset fails with ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by pspierce** [donnex/django-docker-coookiecutter#2]
I realize this is within the donnex/assets, but it does keep this cookiecutter from functioning.
docker-compose version: 1.4.2
Docker version 1.7.1, build 786b29d

I haven't made any changes to the base cookiecutter.

Below is the error:

/gulp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
assets_1          |         this.processing = new Promise(function (resolve, reject) {
assets_1          |                               ^
assets_1          | ReferenceError: Promise is not defined
assets_1          |     at LazyResult.async (/gulp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
assets_1          |     at LazyResult.then (/gulp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
assets_1          |     at DestroyableTransform._transform (/gulp/node_modules/gulp-autoprefixer/index.js:24:6)
assets_1          |     at DestroyableTransform.Transform._read (/gulp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
assets_1          |     at DestroyableTransform.Transform._write (/gulp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
assets_1          |     at doWrite (/gulp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
assets_1          |     at writeOrBuffer (/gulp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
assets_1          |     at DestroyableTransform.Writable.write (/gulp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
assets_1          |     at write (/gulp/node_modules/gulp-compass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
assets_1          |     at flow (/gulp/node_modules/gulp-compass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

**Comment by donnex** [comment]
Yeah, I noticed that myself yesterday. I just committed a fix for this to donnex/assets. It should be possible to pull the new image from Dockerhub soon.

I just updated the assets container to use Node v.4, the old one installed the latest npm packages but they weren't compatible with the old Node version.

I haven't had much time to test it properly. If you do please write back with status :)

**Comment by pspierce** [comment]
I just cloned the donnex/assets and was going to look at fixing it, but now I'll try pulling the new image and I'll let you know.  Thanks.

**Comment by pspierce** [comment]
Looks good now.  Thanks again.

**Comment by donnex** [comment]
Sweet!

I had no idea that someone else than me used this setup :)
